DROP TABLE IF EXISTS friend;  
CREATE TABLE friend (  
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,  
firstname VARCHAR(255)NOT NULL, 
lastname VARCHAR(255)NOT NULL, 
department VARCHAR(255)NOT NULL, 
email VARCHAR(255)NOT NULL, 
country VARCHAR(255)NOT NULL
);

   

